imports:
    - { resource: tables.yml }

services:
    rxu.postsmerging.listener:
        class: rxu\postsmerging\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@dispatcher'
            - '@notification_manager'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@rxu.postsmerging.helper'
            - '%tables.postsmerging%'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
    rxu.postsmerging.helper:
        class: rxu\postsmerging\core\helper
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.postsmerging%'
